### PR TITLE
Add basic dashboard implementation

### LINKED ISSUE #250: Add support for certificate revocation.
It would be nice to have a method for revoking certificates that exist within the Keyvault and were issued by the Acmebot.

An endpoint like /revoke-certificate similar to the /renew-certificate endpoint.

The official recommendation is to use certbot and the private key to revoke as outlined here https://letsencrypt.org/docs/revoking/ however, this requires that one run a certbot instance and download the certificate from the Keyvault.

If possible, a listing of each version from the Keyvaults with their expiration dates would be ideal way to sort them as the version string is not descriptive.

### LINKED ISSUE #341: Add Dashboard page
Implement a new web UI in `/dashboard` to add certificate issuance status and clear links to each UI.

### Features

- [x] Show certificates that are nearing expiration
- [x] Add / Renew certificate in modal
  - [x] Add
  - [x] Renew
  - [x] Revoke #250
  - [x] Details

### Future

- [ ] Execution history of the renewal process
- [ ] Configuration validation (DNS Provider / IAM, etc.)

### PR DESCRIPTION
**Pull request by shibayan**
Ref #341 
Close #250

### CODE REVIEW

**Comment by raphael-liming** [comment]
Hey! Any update on this feature? My team could really use something like this.

Thanks!

**Comment by shibayan** [comment]
No updates.

**Comment by shibayan** [comment]
### Certificate infomation and renew

image

**Comment by adagioajanes** [comment]
This is looking very very good. This is a much better interface than the azure portal key vault, especially for determining simple information about the certificates you have created.

**Comment by shibayan** [comment]
### Add certificate modal

add-certificate

**Comment by shibayan** [comment]
### Revoke certificate

image

**Pull request merged**
