### PR TITLE
Reduce certificate renewal process to once a week

### PR DESCRIPTION
**Pull request by shibayan**

### CODE REVIEW

**Comment by GeorgDangl** [comment]
Hey @shibayan, what's the reason for this change?

Sometimes, I get errors during certificate renewals, e.g. just this Monday I had a failure for a certificate that was then successfully issued again on Wednesday. I fear that having a lower frequency when issuing certificates, we might run into problems in case the task fails multiple times in a row.

The errors are usually something like this, and I suspect this might be a timing issue:

```
"type": "urn:ietf:params:acme:error:dns",
"detail": "During secondary validation: DNS problem: networking error looking up TXT for _acme-challenge.dangl.dev",
"status": 400
```

For reference, I'm using Cloudflare DNS.

**Comment by shibayan** [comment]
This change is due to the increased transfer volume of Azure Storage. Acmebot is automatically deployed from Azure Storage to reduce the need for updates, but the monthly transfer volume has already reached nearly 300GB.

Such DNS errors should be handled as a separate issue, as retries should be immediate.

**Comment by GeorgDangl** [comment]
Oh, I see, thank you for the update! How expensive is that transfer?
Could you maybe put a CDN in front of it, e.g. Cloudflare, to utilize Caching and save on Azure transfer costs?

I'll also increase the donation a bit to compensate for my usage😀

**Comment by shibayan** [comment]
I've changed to once a week with this PR, but I'd like to go back to twice a week if possible while checking the metrics. I will continue to optimize it as much as I can.

The URL of the application zip is set at the time of deployment, so changing it is painful and I feel like I made a mistake.

**Comment by GeorgDangl** [comment]
Ah, I see, so basically it's pointing to somewhere like `mystorage.blob.core.windows.net/file.zip`, and that's hard coded in the deployment for existing installations, right?

You could at least consider going with a CDN for all future installations, but I guess you're aware of that😀

**Pull request merged**
