### PR TITLE
Fixes #493 - Unit tests for DomeneShop provider

### LINKED ISSUE #493: Create unit tests for providers
**Is your feature request related to a problem? Please describe.**
In #492 I suspected a bug in the implementation of `DeleteTxtRecordAsync` for the `DomeneShopProvider`. 

**Describe the solution you'd like**
To verify the bug existed and was fixed, I created a unit test project and implemented tests for all the public methods of `DomeneShopProvider`. Consider implementing tests for the other existing providers to verify the functionality and better describe the provider for developers without access to that provider's API.

**Describe alternatives you've considered**
- Implement changes and deploy a pre-release to test and verify functionality live against the provider's API.
- Create another test project for integration tests with sample data that verifies functionality all the way from the AcmeBot for each provider. This requires a configuration with credentials that should be gitignored and the tests must be easily modified with sample data that suits a developers own domain.

**Additional context**
The tests I've implemented will be sent in a separate PR.
image

### PR DESCRIPTION
**Pull request by eloekset**
A test project using XUnit and Moq to verify the functionality of all public methods of the DomeneShop provider. Sample data for three domains is included as json files, and all values are dummy values, but still exactly like the v0 of DomeneShop API.

Helped me verify and fix a bug in this provider.

### CODE REVIEW

**Comment by eloekset** [comment]
I can rebase on master if you want to merge #491 before this one.

**Comment by shibayan** [comment]
I believe that the correctness of the DNS Provider can only be verified by running the actual DNS API. I don't see the value in testing code using a mock API.

**Comment by eloekset** [comment]
I use sample messages copied from the request and response messages in Postman.
image

It helps, by letting me debug the code and verify the functionality of the provider before deploying the application.

**Comment by shibayan** [comment]
In my opinion mocking the DNS provider API is pointless and doesn't change the fact that you need to hit the actual API. This PR will not be merged.

**Pull request closed without merging**
