### PR TITLE
Adding Custom DNS Provider model

### PR DESCRIPTION
**Pull request by shibayan**
Because of the high maintenance cost of integrating DNS providers into Acmebot, I will change to using HTTP-based custom providers for all but the major DNS providers, and implement the necessary APIs by ourselves.

I will no longer accept pull requests for non-major DNS providers.

### CODE REVIEW

**Comment by ypid-geberit** [comment]
I think the approach with a custom DNS provider is a good one. We would be interested in that feature. Looks like only the docs are missing. I guess you are waiting for feedback before you consider merging and releasing that? Can you point me to API docs that you expect so that I can consider testing it?

**Comment by shibayan** [comment]
The Custom DNS Provider API has not been defined yet, so there is no documentation available. It will be available after this PR is merged.

However, since there are very few requests for the Custom DNS Provider, the work has a low priority.

**Comment by johste93** [comment]
Found this plugin today, just want to say we need this feature. We're using dnsimple.

**Comment by ypid-geberit** [comment]
I now took a deeper look at your work @shibayan to figure out how much work is needed to test/use the CustomDnsProvider. The implementation and API definition are already there and the CI test confirms that it builds.

The `CustomDnsProvider` exposes 2 app settings:

* `Acmebot:CustomDns:PropagationSeconds`
* `Acmebot:CustomDns:Endpoint`
  *  Base URL of the CustomDNS endpoint.

The code assumes that there is a HTTP(S) REST API endpoint that supports the following methods:

* `GET /zones`
  * Should return a JSON object that can be deserialized into a list of DnsZone objects, ref: https://github.com/shibayan/keyvault-acmebot/blob/master/KeyVault.Acmebot/Providers/DnsZone.cs
  * Example:

    ```json
    [
      {
        "Id": "example_net",
        "Name": "example",
        "NameServers": [
          "203.0.113.23",
          "203.0.113.42",
        ]
      }
    ]
    ```

* `POST /records/create`
  * Should accept a JSON object like this example:
  ```json
  {
    "Id": "example_net",
    "recordName": "_acme-challenge.example.net",
    "values": ["667drNmQL3vX6bu8YZlgy0wKNBlCny8yrjF1lSaUndc"]
  }
  ```
  * This needs to create a TXT record at `_acme-challenge.example.net` which is then used by the CA to verify domain control.

* `POST /records/delete`
  * Should accept a JSON object like this example:
  ```json
  {
    "Id": "example_net",
    "recordName": "_acme-challenge.example.net"
  }
  ```
  * This needs to delete/cleanup the TXT record at _acme-challenge.example.net.


To test this, I would need to fork your branch/this pull request, change "WEBSITE_RUN_FROM_PACKAGE" in https://github.com/shibayan/keyvault-acmebot/blob/master/azuredeploy.json to a zip file I have build with the CustomDnsProvider included.

Am I missing something? Could you publish the zip file/modified azuredeploy.json? I am a Linux developer and ops guy unfamiliar with this Mircosoft dev environment.

If I can give you feedback on the API design, I would propose those changes:

* `POST /records/example_net`
  ```json
  {
    "recordName": "_acme-challenge.example.net",
    "values": ["667drNmQL3vX6bu8YZlgy0wKNBlCny8yrjF1lSaUndc"]
  }
  ```

* `DELETE /records/example_net`
  * Should accept a JSON object like this example:
  ```json
  {
    "recordName": "_acme-challenge.example.net"
  }
  ```

A open question is authentication. I propose to add an app setting `Acmebot:CustomDns:ApiToken` with the same semantics as `Acmebot:Cloudflare:ApiToken`. Which would boil down to this code line getting added to this pull request:

```csharp
_httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiToken);
```

Ref: https://github.com/shibayan/keyvault-acmebot/blob/ea3b49e4a2b46a0093545a0d08c22a8fee2437fe/KeyVault.Acmebot/Providers/CloudflareProvider.cs

**Comment by shibayan** [comment]
I have made significant changes to the API specification based on feedback. The API should now be easier to use than before.

https://github.com/shibayan/keyvault-acmebot/wiki/DNS-Provider-Configuration#custom-dns-preview

**Comment by ypid-geberit** [comment]
Thanks very much! I reviewed your changes again. I am not a C# dev but what I understand looks good to me. Can we deploy this to Azure somehow for testing?

**Comment by shibayan** [comment]
It will be available after the PR is merged after a minimum of checking. However, it will be a preview feature for a while.

If you want to try it out right now, you can clone the repository, switch branches, and deploy it manually to Azure Functions to make it available.

**Pull request merged**
